{{- if .Values.validatingWebhook.enabled -}}
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "kubenab.fullname" . }}-validate
  labels:
{{ include "kubenab.labels" . | indent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/{{ include "kubenab.servingCertificate" . }}"
webhooks:
- name: kubenab-validate.jfrog.com
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  failurePolicy: Ignore
  clientConfig:
    service:
      name: {{ include "kubenab.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: "/validate"
{{- end -}}
